//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderedItem
    {
        public int OrderedItemId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<decimal> BookPrice { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
    
        public virtual User User { get; set; }
    }
}
